### ISSUE TITLE
MCL-1 is not capped at C terminus?

### ISSUE THREAD

**Issue by IAlibay** [openforcefield/protein-ligand-benchmark#75]
Linked to #68, MCL-1 does not have a cap at the C terminus even though 4HW3 states that the protein is missing residues 322 and 323.

Is this intentional?

**Comment by bobym** [comment]
Looking back at my notes, this stems from a misunderstanding of the assay protocol. The authors assayed the ligands using an MCL1 construct that had the last 5 AA deleted. I misread the residues in the 4WH3 structure and thought the missing residues were a part of that deletion because the numbering in their SI and the PDB are different. Opening a PR to fix this now.

**Comment by ijpulidos** [comment]
This has been solved via #82
